name: Flutter Build and Setup

on:
  push:
    branches:
      - main

jobs:
  build_and_setup:
    runs-on: macos-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check Flutter version
        run: flutter doctor -v
      - name: Flutter Get Packages
        run: flutter pub get
      - name: Flutter Build debug APK
        run: flutter build apk --debug

      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install TestSweets
        run: |
          brew tap filledstacks/tap
          brew install testsweets
      - name: Start Emulator and Run TestSweets
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: testsweets run -p qA5ua2TOgxBtMGcSVBGE -a build/app/outputs/flutter-apk/app-debug.apk
