name: Run TestSweets Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testsweets_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TestSweets
        run: |
          brew install testsweets

      - name: Run TestSweets Tests
        run: /usr/local/bin/testsweets run -p qA5ua2TOgxBtMGcSVBGE -a build/app/outputs/flutter-apk/app-debug.apk
