name: Flutter Build and Setup

on:
  push:
    branches:
      - main

jobs:
  build_and_setup:
    runs-on: macos-latest
    env:
      ANDROID_SDK_ROOT: $HOME/Library/Android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check Flutter version
        run: flutter doctor -v

      - name: Export ADB and xcrun paths
        run: |
          echo "export PATH=\$PATH:$HOME/Library/Android/sdk/platform-tools" >> $GITHUB_ENV
          echo "export PATH=\$PATH:/usr/bin/xcrun" >> $GITHUB_ENV

      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Create Android emulator
        run: |
          echo "Creating Android emulator"
          echo "no" | $ANDROID_SDK_ROOT/tools/bin/avdmanager --verbose create avd --force --name emulator-5554 --package "system-images;android-29;google_apis;x86" --tag "google_apis" --abi "x86"

      - name: Start Android emulator
        run: |
          echo "Starting Android emulator"
          $ANDROID_SDK_ROOT/emulator/emulator -avd emulator-5554 -no-snapshot -no-accel &

      - name: Wait for emulator to start
        run: |
          echo "Waiting for emulator to start"
          $ANDROID_SDK_ROOT/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Run Flutter App on Emulator
        run: flutter run --debug
